export default Screen = {
    HOME_STACK: 'HOME_STACK',
    HOME: 'HOME',
    NETWORK_STACK: 'NETWORK_STACK',
    NETWORK: 'NETWORK',
    POST_STACK: 'POST_STACK',
    POST: 'POST',
    NOTIFICATION_STACK: 'NOTIFICATION_STACK',
    NOTIFICATION: 'NOTIFICATION',
    JOB_STACK: 'JOB_STACK',
    JOB: 'JOB',
    PROFILE: 'PROFILE'
}